const en={title:'Session board',subtitle:'Your agents, one workspace',board:'Board',list:'List',search:'Search tasks, projects or session IDs',filter:'Filter',sort:'Sort',group:'Group',fields:'Fields',newTask:'New task',refresh:'Refresh',all:'All',active:'In use & tracked',history:'Include recent history',engine:'Engine',state:'Status',cwd:'Project',updated_at:'Updated',session_id:'Session ID',summary:'Activity',attention:'Needs action',running:'Running',queued:'Queued / draft',unread:'Completed · unread',completed:'Completed',idle:'Idle · viewed',interrupted:'Interrupted',unknown:'Unconfirmed',noProject:'No project',none:'No grouping',oldest:'Oldest first',recent:'Recently updated',priority:'Action needed first',empty:'No matching tasks',emptyColumn:'No tasks',clear:'Reset filters',synced:'Last sync',stale:'Sync failed. Showing the last known snapshot.',loading:'Loading sessions…',copy:'Copy task reference',copied:'Task reference copied. Paste it into chat.',copyFailed:'Clipboard unavailable',open:'Open session',native:'Open in Codex App',back:'Back to board',prompt:'Describe the task',taskTitle:'Task title (optional)',create:'Create and run',creating:'Creating…',transport:'Execution channel',app:'Original App',cli:'Native CLI',readOnly:'Read only',write:'Allow workspace edits',mode:'Permissions',cancel:'Cancel',hermesNew:'Open new Hermes chat',hermesHint:'Continue in the new Hermes chat to enter and run your task.',claudeHint:'New Claude sessions use native CLI; creating a Claude Desktop window is not supported.',historyLimit:'Recent local history loaded',detail:'Task session',unavailable:'Session unavailable',read:'Mark result as read',copiedHint:'A task reference stays live in chat.',count:'tasks',legacy:'Session collaboration',boardView:'Task board',reduced:'Status motion respects reduced-motion settings.'}
const zh={...en,title:'Session 任务看板',subtitle:'所有 Agent，会话一目了然',board:'看板',list:'列表',search:'搜索任务、项目或 Session ID',filter:'筛选',sort:'排序',group:'分组',fields:'显示字段',newTask:'新建任务',refresh:'刷新',all:'全部',active:'正在使用与已跟踪',history:'包含近期历史',engine:'引擎',state:'状态',cwd:'项目',updated_at:'更新时间',session_id:'Session ID',summary:'最新动态',attention:'需要操作',running:'运行中',queued:'排队 / 待开始',unread:'完成 · 未查看',completed:'已完成',idle:'空闲 · 已查看',interrupted:'已中断',unknown:'状态待确认',noProject:'无项目',none:'不分组',oldest:'最早更新优先',recent:'最近更新优先',priority:'待操作优先',empty:'没有符合条件的任务',emptyColumn:'暂无任务',clear:'重置筛选',synced:'最近同步',stale:'同步失败，显示上次已知状态。',loading:'正在读取会话…',copy:'复制任务引用',copied:'已复制，可粘贴到对话中。',copyFailed:'无法访问剪贴板',open:'打开会话',native:'在 Codex App 中打开',back:'返回看板',prompt:'描述要执行的任务',taskTitle:'任务标题（可选）',create:'创建并运行',creating:'正在创建…',transport:'执行通道',app:'原生 App',cli:'原生 CLI',readOnly:'只读分析',write:'允许修改工作区',mode:'执行权限',cancel:'取消',hermesNew:'打开新 Hermes 对话',hermesHint:'进入新的 Hermes 对话后，输入任务即可开始执行。',claudeHint:'新建 Claude 会话使用原生 CLI，目前不支持创建 Claude Desktop 窗口。',historyLimit:'已载入近期本地历史',detail:'任务会话',unavailable:'会话暂不可用',read:'标记结果已查看',copiedHint:'任务引用在对话中持续同步状态。',count:'个任务',legacy:'会话协作',boardView:'任务看板',reduced:'状态动画遵循系统减少动态效果设置。'}
const hant={...zh,title:'Session 任務看板',subtitle:'所有 Agent，會話一目了然',list:'清單',search:'搜尋任務、專案或 Session ID',filter:'篩選',sort:'排序',group:'分組',fields:'顯示欄位',newTask:'新增任務',refresh:'重新整理',all:'全部',active:'使用中與已追蹤',history:'包含近期歷史',engine:'引擎',state:'狀態',cwd:'專案',updated_at:'更新時間',summary:'最新動態',attention:'需要操作',running:'執行中',queued:'排隊 / 待開始',unread:'完成 · 未檢視',completed:'已完成',idle:'閒置 · 已檢視',interrupted:'已中斷',unknown:'狀態待確認',noProject:'無專案',none:'不分組',oldest:'最早更新優先',recent:'最近更新優先',priority:'待操作優先',empty:'沒有符合條件的任務',emptyColumn:'暫無任務',clear:'重設篩選',synced:'最近同步',stale:'同步失敗，顯示上次已知狀態。',loading:'正在讀取會話…',copy:'複製任務引用',copied:'已複製，可貼到對話中。',copyFailed:'無法存取剪貼簿',open:'開啟會話',native:'在 Codex App 中開啟',back:'返回看板',prompt:'描述要執行的任務',taskTitle:'任務標題（選填）',create:'建立並執行',creating:'正在建立…',transport:'執行通道',app:'原生 App',mode:'執行權限',readOnly:'唯讀分析',write:'允許修改工作區',cancel:'取消',hermesNew:'開啟新 Hermes 對話',hermesHint:'進入新的 Hermes 對話後，輸入任務即可開始執行。',claudeHint:'新增 Claude 會話使用原生 CLI，目前不支援建立 Claude Desktop 視窗。',historyLimit:'已載入近期本機歷史',detail:'任務會話',unavailable:'會話暫時無法使用',read:'標記結果已檢視',copiedHint:'任務引用在對話中持續同步狀態。',count:'個任務',legacy:'會話協作',boardView:'任務看板',reduced:'狀態動畫遵循系統減少動態效果設定。'}
const ja={...en,title:'セッションボード',subtitle:'すべてのエージェントをひとつの場所で',board:'ボード',list:'リスト',search:'タスク、プロジェクト、ID を検索',filter:'絞り込み',sort:'並べ替え',group:'グループ',fields:'表示項目',newTask:'新規タスク',refresh:'更新',all:'すべて',active:'使用中・追跡中',history:'最近の履歴を含める',engine:'エンジン',state:'状態',cwd:'プロジェクト',updated_at:'更新日時',summary:'最近の動作',attention:'操作が必要',running:'実行中',queued:'待機 / 下書き',unread:'完了・未読',completed:'完了',idle:'待機・確認済み',interrupted:'中断',unknown:'未確認',noProject:'プロジェクトなし',none:'グループ化なし',oldest:'古い更新順',recent:'新しい更新順',priority:'要対応を優先',empty:'該当するタスクがありません',emptyColumn:'タスクなし',clear:'条件をリセット',synced:'最終同期',stale:'同期失敗。前回の状態を表示しています。',loading:'セッションを読み込み中…',copy:'参照をコピー',copied:'コピーしました。チャットに貼り付けてください。',copyFailed:'クリップボードにアクセスできません',open:'セッションを開く',native:'Codex App で開く',back:'ボードに戻る',prompt:'実行するタスク',taskTitle:'タスク名（任意）',create:'作成して実行',creating:'作成中…',transport:'実行経路',app:'元の App',cli:'ネイティブ CLI',readOnly:'読み取り専用',write:'作業領域の編集を許可',mode:'権限',cancel:'キャンセル',hermesNew:'新しい Hermes チャット',hermesHint:'新しい Hermes チャットにタスクを入力して実行します。',claudeHint:'新しい Claude セッションは CLI を使用します。Desktop ウィンドウの作成は未対応です。',historyLimit:'読み込んだ最近の履歴',detail:'タスクセッション',unavailable:'セッションを利用できません',read:'結果を既読にする',copiedHint:'チャット内の参照も状態を同期します。',count:'件',legacy:'セッション連携',boardView:'タスクボード',reduced:'アニメーションは視差効果の設定に従います。'}
Object.assign(en,{fields:'Field settings',boardView:'Unified board',titleField:'Title',completion:'Quick filter',unfinished:'Unfinished',finished:'Completed',allTasks:'All tasks',scope:'Session scope',filterField:'Field',operator:'Operator',filterValue:'Value',chooseValue:'Choose values',enterValue:'Enter a value',matchLabel:'Match',matchAll:'All conditions',matchAny:'Any condition',when:'If',and:'And',or:'Or',addCondition:'Add condition',removeCondition:'Remove condition',clearConditions:'Clear',filterHint:'Add conditions to filter sessions. Empty conditions are ignored.',contains:'Contains',notContains:'Does not contain',is:'Is any of',isNot:'Is not',emptyValue:'Is empty',notEmpty:'Is not empty',on:'On date',before:'Before date',after:'After date',restoreFields:'Reset',fieldsHint:'Drag to reorder; use the eye to show or hide fields.',visibility:'Show field',moveUp:'Move up',moveDown:'Move down',dragField:'Drag to reorder',managed:'Hub tracked',live:'Live source',yes:'Yes',no:'No'})
Object.assign(zh,{fields:'字段配置',boardView:'统一看板',titleField:'任务标题',completion:'快捷筛选',unfinished:'未完成',finished:'已完成',allTasks:'全部任务',scope:'会话范围',filterField:'筛选字段',operator:'条件',filterValue:'筛选值',chooseValue:'请选择（可多选）',enterValue:'请输入筛选值',matchLabel:'匹配方式',matchAll:'满足全部条件',matchAny:'满足任一条件',when:'当',and:'且',or:'或',addCondition:'添加条件',removeCondition:'删除条件',clearConditions:'清空',filterHint:'添加条件筛选会话，未填写的条件不生效。',contains:'包含',notContains:'不包含',is:'等于 / 属于',isNot:'不等于 / 不属于',emptyValue:'为空',notEmpty:'不为空',on:'日期为',before:'早于日期',after:'晚于日期',restoreFields:'恢复默认',fieldsHint:'拖动调整顺序，点击眼睛切换字段显隐。',visibility:'显示字段',moveUp:'上移',moveDown:'下移',dragField:'拖动调整顺序',managed:'Hub 已跟踪',live:'实时来源',yes:'是',no:'否'})
Object.assign(hant,{fields:'欄位設定',boardView:'統一看板',titleField:'任務標題',completion:'快捷篩選',unfinished:'未完成',finished:'已完成',allTasks:'全部任務',scope:'會話範圍',filterField:'篩選欄位',operator:'條件',filterValue:'篩選值',chooseValue:'請選擇（可多選）',enterValue:'請輸入篩選值',matchLabel:'匹配方式',matchAll:'符合全部條件',matchAny:'符合任一條件',when:'當',and:'且',or:'或',addCondition:'新增條件',removeCondition:'刪除條件',clearConditions:'清空',filterHint:'新增條件篩選會話，未填寫的條件不生效。',contains:'包含',notContains:'不包含',is:'等於 / 屬於',isNot:'不等於 / 不屬於',emptyValue:'為空',notEmpty:'不為空',on:'日期為',before:'早於日期',after:'晚於日期',restoreFields:'恢復預設',fieldsHint:'拖動調整順序，點擊眼睛切換欄位顯隱。',visibility:'顯示欄位',moveUp:'上移',moveDown:'下移',dragField:'拖動調整順序',managed:'Hub 已追蹤',live:'即時來源',yes:'是',no:'否'})
Object.assign(ja,{fields:'項目設定',boardView:'統合ボード',titleField:'タスク名',completion:'クイック絞り込み',unfinished:'未完了',finished:'完了',allTasks:'すべてのタスク',scope:'セッション範囲',filterField:'項目',operator:'条件',filterValue:'値',chooseValue:'選択（複数可）',enterValue:'値を入力',matchLabel:'一致方法',matchAll:'すべての条件',matchAny:'いずれかの条件',when:'条件',and:'かつ',or:'または',addCondition:'条件を追加',removeCondition:'条件を削除',clearConditions:'クリア',filterHint:'条件を追加してください。空の条件は無視します。',contains:'含む',notContains:'含まない',is:'一致する',isNot:'一致しない',emptyValue:'空である',notEmpty:'空ではない',on:'指定日',before:'指定日より前',after:'指定日より後',restoreFields:'リセット',fieldsHint:'ドラッグで並べ替え、目のアイコンで表示を切り替えます。',visibility:'項目を表示',moveUp:'上へ',moveDown:'下へ',dragField:'ドラッグで並べ替え',managed:'Hub 追跡中',live:'ライブ接続',yes:'はい',no:'いいえ'})
// Task title and the board's page title have separate translation keys.
export const boardLocales={en,zh,'zh-hant':hant,ja}
Object.assign(en,{nativeSelected:'Task selected in Codex. Switch to its window.'})
Object.assign(zh,{nativeSelected:'已在 Codex 中选中原任务，请切换到 Codex 窗口。'})
Object.assign(hant,{nativeSelected:'已在 Codex 中選取原任務，請切換到 Codex 視窗。'})
Object.assign(ja,{nativeSelected:'Codex で元のタスクを選択しました。ウィンドウを切り替えてください。'})
Object.assign(en,{closed:'Closed flag',openTask:'Open',closedTask:'Closed',closeTask:'Close task',reopenTask:'Reopen task',closeHint:'Board flag only; does not stop or archive the session',nativeOpening:'Opening Codex…',nativeOpened:'Opened the original task in Codex.',nativeFailed:'Codex did not confirm navigation.'})
Object.assign(zh,{closed:'是否关闭',openTask:'已开启',closedTask:'已关闭',closeTask:'关闭任务',reopenTask:'重新开启任务',closeHint:'仅修改看板标记，不停止或归档原会话',nativeOpening:'正在打开 Codex…',nativeOpened:'已在 Codex 中打开原任务。',nativeFailed:'Codex 未确认跳转成功。'})
Object.assign(hant,{closed:'是否關閉',openTask:'已開啟',closedTask:'已關閉',closeTask:'關閉任務',reopenTask:'重新開啟任務',closeHint:'僅修改看板標記，不停止或封存原會話',nativeOpening:'正在開啟 Codex…',nativeOpened:'已在 Codex 中開啟原任務。',nativeFailed:'Codex 未確認跳轉成功。'})
Object.assign(ja,{closed:'クローズ状態',openTask:'オープン',closedTask:'クローズ',closeTask:'タスクを閉じる',reopenTask:'タスクを再開',closeHint:'ボード上の印のみ。セッションを停止・アーカイブしません',nativeOpening:'Codex を開いています…',nativeOpened:'元のタスクを Codex で開きました。',nativeFailed:'Codex での表示を確認できませんでした。'})
Object.assign(en,{sessionInfo:'Session details',continueOriginal:'Continue original Codex task',continuePlaceholder:'Continue this task… Ctrl / ⌘ + Enter to send',originalExecution:'Runs in the original Codex App. Approvals and stop controls remain there.',sendOriginal:'Send to original task ↑',sendingOriginal:'Submitting…',checkDelivery:'Check delivery',deliveryUnknown:'Delivery response is unconfirmed. Check using the same request; it will not enqueue a duplicate.',nativeAction:'Open Codex to inspect and handle this task.',delivery_queued:'Queued for delivery',delivery_sending:'Delivering to Codex',delivery_delivered:'Accepted by Codex',delivery_running:'Codex is working',delivery_completed:'Turn finished',delivery_needs_attention:'Needs attention',delivery_delivery_uncertain:'Delivery unconfirmed'})
Object.assign(zh,{sessionInfo:'会话详情',continueOriginal:'继续原 Codex 任务',continuePlaceholder:'继续处理这个任务… Ctrl / ⌘ + Enter 发送',originalExecution:'沿用 Codex 原任务执行；审批和停止操作请在 Codex 中处理。',sendOriginal:'发送到原任务 ↑',sendingOriginal:'正在提交…',checkDelivery:'核对发送结果',deliveryUnknown:'尚未确认发送回执。核对时会使用同一请求，不会重复排队。',nativeAction:'请打开 Codex 检查并处理。',delivery_queued:'消息已排队',delivery_sending:'正在发送给 Codex',delivery_delivered:'Codex 已接收',delivery_running:'Codex 正在处理',delivery_completed:'本轮已结束',delivery_needs_attention:'需要处理',delivery_delivery_uncertain:'发送结果待确认'})
Object.assign(hant,{sessionInfo:'會話詳情',continueOriginal:'繼續原 Codex 任務',continuePlaceholder:'繼續處理這個任務… Ctrl / ⌘ + Enter 傳送',originalExecution:'沿用 Codex 原任務執行；核准和停止操作請在 Codex 中處理。',sendOriginal:'傳送到原任務 ↑',sendingOriginal:'正在提交…',checkDelivery:'核對傳送結果',deliveryUnknown:'尚未確認傳送回執。核對時會使用同一請求，不會重複排隊。',nativeAction:'請開啟 Codex 檢查並處理。',delivery_queued:'訊息已排隊',delivery_sending:'正在傳送給 Codex',delivery_delivered:'Codex 已接收',delivery_running:'Codex 正在處理',delivery_completed:'本輪已結束',delivery_needs_attention:'需要處理',delivery_delivery_uncertain:'傳送結果待確認'})
Object.assign(ja,{sessionInfo:'セッション詳細',continueOriginal:'元の Codex タスクを続行',continuePlaceholder:'このタスクを続行… Ctrl / ⌘ + Enter で送信',originalExecution:'元の Codex タスクで実行。承認と停止は Codex で操作してください。',sendOriginal:'元のタスクに送信 ↑',sendingOriginal:'送信中…',checkDelivery:'送信結果を確認',deliveryUnknown:'送信結果が未確認です。同じリクエストで確認し、重複登録しません。',nativeAction:'Codex を開いて確認してください。',delivery_queued:'送信待ち',delivery_sending:'Codex に送信中',delivery_delivered:'Codex が受信済み',delivery_running:'Codex が処理中',delivery_completed:'ターン終了',delivery_needs_attention:'対応が必要',delivery_delivery_uncertain:'送信結果が未確認'})

Object.assign(en,{insertImages:'Insert images',previewImage:'Preview image',closePreview:'Close preview',removeImage:'Remove image',imageLimit:'Up to 5 images per message.',imageTypes:'PNG, JPEG, WebP · up to 8 MB each',imageReadFailed:'Could not read image.',uploadingImages:'Preparing images…',copyMessage:'Copy message',copiedMessage:'Copied',processing:'Execution records'})
Object.assign(zh,{insertImages:'插入图片',previewImage:'预览图片',closePreview:'关闭预览',removeImage:'移除图片',imageLimit:'每条消息最多 5 张图片。',imageTypes:'PNG、JPEG、WebP · 每张最多 8 MB',imageReadFailed:'无法读取图片。',uploadingImages:'正在准备图片…',copyMessage:'复制消息',copiedMessage:'已复制',processing:'执行过程'})
Object.assign(hant,{insertImages:'插入圖片',previewImage:'預覽圖片',closePreview:'關閉預覽',removeImage:'移除圖片',imageLimit:'每條訊息最多 5 張圖片。',imageTypes:'PNG、JPEG、WebP · 每張最多 8 MB',imageReadFailed:'無法讀取圖片。',uploadingImages:'正在準備圖片…',copyMessage:'複製訊息',copiedMessage:'已複製',processing:'執行過程'})
Object.assign(ja,{insertImages:'画像を挿入',previewImage:'画像を表示',closePreview:'プレビューを閉じる',removeImage:'画像を削除',imageLimit:'1 メッセージにつき最大 5 枚。',imageTypes:'PNG、JPEG、WebP · 各 8 MB まで',imageReadFailed:'画像を読み取れません。',uploadingImages:'画像を準備中…',copyMessage:'メッセージをコピー',copiedMessage:'コピー済み',processing:'実行履歴'})

Object.assign(en,{documentPreview:'Document preview',changedFiles:'Changed files',editedFiles:'Edited {count} files',moreFiles:'Show {count} more files',collapseFiles:'Show fewer files'})
Object.assign(zh,{documentPreview:'文档预览',changedFiles:'修改文件列表',editedFiles:'已编辑 {count} 个文件',moreFiles:'再显示 {count} 个文件',collapseFiles:'收起文件列表'})
Object.assign(hant,{documentPreview:'文件預覽',changedFiles:'修改檔案清單',editedFiles:'已編輯 {count} 個檔案',moreFiles:'再顯示 {count} 個檔案',collapseFiles:'收起檔案清單'})
Object.assign(ja,{documentPreview:'ドキュメント表示',changedFiles:'変更ファイル',editedFiles:'{count} ファイルを編集',moreFiles:'さらに {count} ファイルを表示',collapseFiles:'ファイル一覧を折りたたむ'})

Object.assign(en,{claudeHint:'Original App opens a Claude Code draft. Check the project and send it in Claude; the session then appears here. CLI runs separately.',claudePrepare:'Prepare in Claude App',claudeDraftReady:'Claude draft requested. Check the project and press Send in Claude; refresh the board after it starts.',claudeOpenRequested:'Requested the original Claude session. If Claude shows its home page, select this task there.',claudeContinueHint:'Keep the original Claude Code session open. Peer messages use its context and permissions; approvals stay in Claude.'})
Object.assign(zh,{claudeHint:'原生 App 会打开 Claude Code 草稿。在 Claude 确认项目并发送后，会话会同步到这里；CLI 则单独执行。',claudePrepare:'在 Claude App 准备草稿',claudeDraftReady:'已请求打开 Claude 草稿。请在 Claude 确认项目并发送，开始后刷新看板。',claudeOpenRequested:'已请求打开原 Claude 会话；如果停留在首页，请在 Claude 中选择此任务。',claudeContinueHint:'保持原 Claude Code 会话打开。消息沿用其上下文与权限；审批请在 Claude 中处理。'})
Object.assign(hant,{claudeHint:'原生 App 會開啟 Claude Code 草稿。在 Claude 確認專案並傳送後，會話會同步到這裡；CLI 則單獨執行。',claudePrepare:'在 Claude App 準備草稿',claudeDraftReady:'已請求開啟 Claude 草稿。請在 Claude 確認專案並傳送，開始後重新整理看板。',claudeOpenRequested:'已請求開啟原 Claude 會話；如果停留在首頁，請在 Claude 中選擇此任務。',claudeContinueHint:'保持原 Claude Code 會話開啟。訊息沿用其上下文與權限；核准請在 Claude 中處理。'})
Object.assign(ja,{claudeHint:'Claude Code で下書きを開きます。プロジェクトを確認して送信するとここに同期されます。CLI は別途実行します。',claudePrepare:'Claude App で下書きを準備',claudeDraftReady:'Claude でプロジェクトを確認し送信してください。開始後にボードを更新します。',claudeOpenRequested:'元の Claude セッションを開くよう要求しました。ホームが表示された場合は Claude でタスクを選択してください。',claudeContinueHint:'元の Claude Code セッションを開いておいてください。コンテキストと権限を引き継ぎ、承認は Claude で行います。'})
